### ISSUE TITLE
Panorama fix?

### ISSUE THREAD

**Issue by Mante-z** [ekknod/NV#1]
Hey :)
Quick question

Do you know how to update it to panorama? i tried but no luck

Thanks

Also does not work on faceit client anymore with -legacyscaleformui :(

**Comment by DrInsidious** [comment]
ye it would be sad if this would be the end of this awesome cheat

**Comment by Mante-z** [comment]
@DrInsidious True true

**Comment by DrInsidious** [comment]
lol didnt expect that

**Comment by Mante-z** [comment]
what

**Comment by DrInsidious** [comment]
an instant answer from you

**Comment by Mante-z** [comment]
haha ikr, i got an email and when its from github i like instant respond

**Comment by DrInsidious** [comment]
alright

**Comment by krypton7447** [comment]
sad

**Comment by ekknod** [comment]
@DrInsidious @ziez456, pushed update. i can't test it right now, can you guys do it?

**Comment by Mante-z** [comment]
@eknod i will try ASAP

**Comment by Mante-z** [comment]
> @DrInsidious @ziez456, pushed update. i can't test it right now, can you guys do it?

Not working :) tested it

**Comment by ekknod** [comment]
@ziez456 thanks for testing it anyways, i will fix and test it tomorrow.

**Comment by Mante-z** [comment]
> @ziez456 thanks for testing it anyways, i will fix and test it tomorrow.

Thanks alot bro!

**Comment by ekknod** [comment]
@ziez456 for me it was working fine, i think you forgot update the repository before compiling.
anyways, i uploaded precompiled binary to uc.

**Comment by DrInsidious** [comment]
Oof didnt expect a fix im so happy

**Comment by Mante-z** [comment]
I still dont know why it doesnt work for me
