### ISSUE TITLE
i have some issue question

### ISSUE THREAD

**Issue by AZLGOOD** [ekknod/NV#6]
Hello
Can you give me your string decrypt src from your NV project ?
do i need to add junk code to this ?
i want have your skype/discord/email contact you talk with other questions.

**Comment by ekknod** [comment]
Hi, i suggest you to use RtlCrc32 instead:
https://github.com/ekknod/nv_v2/blob/master/nv_v2/main.c#L48
much easier to use, already built in windows os.

you can contact me in youtube :)
